version: "3.0"
services:
  test:
    image: beamcorp/bql-dev
    container_name: bql-test
    ports: 
      - 3000:3000
    volumes: 
      - .:/src/
      - node_modules:/src/node_modules
    command: npm run test
volumes:
  node_modules:
  test-db-volume:

# to be added to scripts in package.json: "test": "NODE_ENV=test jest --coverage"
# we have no tests written thus far